<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="copy">
	<div class="footer content">
		<div class="left">
			<span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
		</div>
		<div class="right">
			<div class="img">
				<img class="img-responsive" src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/cdz-footer-payment.png" alt="Accept Payment">
			</div>
		</div>
	</div>
</div>
