<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) {
    $type = 'widget-new-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = __('New Released Products');
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = true;
}
?>

<?php if ($exist):?>
    <div class="block widget block-new-products <?=  $mode ?>">
        <div class="cdz-block-title">
            <div class="b-title">
                <h3><?php echo $title ?></h3>
            </div>
            <div class="title-desc">Duis eget malesuada metus. Donec fringilla suscipit efficitur.</div>
            <div class="title-button"><a class="viewall" href="#">view all</a></div>
        </div>
        <div class="block-content">
            <?=  '<!-- ' . $image . '-->' ?>
            <div class="custom-products-<?=  $mode ?> <?=  $mode ?>">
                <ol class="slider-new owl-carousel product-items <?=  $type ?>">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <?=  ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                        <div class="product-item-info">
                            <a href="<?=  $block->getProductUrl($_item) ?>" class="product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?=  $block->getProductUrl($_item) ?>"
                                       class="product-item-link">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                
                                <div class="add-description product-item-description">
                                   <?php $des = $_item->getData("description"); ?>
                                   <?php $leng = strlen($des); ?>
                                   <?php echo substr($des,0,40); ?>
                                   <?php if($leng > 40) echo '...'; ?>
                                </div>
                                <?php
                                echo $block->getProductPriceHtml($_item, $type);
                                ?>

                                <?php if ($templateType): ?>
                                    <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                <?php endif; ?>
                                
                                <?php if ($showWishlist || $showCompare || $showCart): ?>
                                    <div class="product-item-actions">
                                        <?php if ($showCart): ?>
                                            <div class="actions-secondary" data-role="add-to-links">
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="cs-links add-action-tocart-primary"
                                                                data-mage-init='{"redirectUrl":{"url":"<?=  $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?=  __('Add to Cart') ?>">
                                                            <span><?=  __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php
                                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="cs-links add-action-tocart-primary"
                                                                data-post='<?=  $postData ?>'
                                                                type="button" title="<?=  __('Add to Cart') ?>">
                                                            <span><?=  __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?=  __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="stock unavailable"><span><?=  __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            
                                        <?php endif; ?>
                                        <?php if ($showWishlist || $showCompare): ?>
                                            
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?=  $block->getAddToWishlistParams($_item) ?>'
                                                       class="cs-links action towishlist" data-action="add-to-wishlist"
                                                       title="<?=  __('Add to Wish List') ?>">
                                                        
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                    <a href="#" class="cs-links action tocompare"
                                                       data-post='<?=  $compareHelper->getPostDataParams($_item) ?>'
                                                       title="<?=  __('Add to Compare') ?>">
                                                        
                                                    </a>
                                                <?php endif; ?>
                                                <a href="javascript:void(0)" class="cs-links quick">
                                                    
                                                </a>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <?= ($iterator == count($items)+1) ? '</li>' : '' ?>
                    <?php endforeach ?>
                </ol>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
<?php endif;?>
