

<!-- <div class="cdz-best-seller-wrap">
	<div class="cdz-block-title">
		<div class="b-title"><h3>Best Seller</h3></div>
		<div class="title-desc">Duis eget malesuada metus. Donec fringilla suscipit efficitur.</div>
	</div>
	<div id="tabs" class="tabs">
		<nav>
			<ul>
				<li><a href="#section-1" class="icon-shop"><span>Tables & Chairs</span></a></li>
				<li><a href="#section-2" class="icon-cup"><span>Home Accessories</span></a></li>
				<li><a href="#section-3" class="icon-food"><span>Kichen</span></a></li>
			</ul>
		</nav>
		<div class="content">
			<section id="section-1">
				<div class="custom-grid-pr">
					<ul class="product-list">
						<li class="big-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner06.jpg" alt="img01" />
							<h3>Sushi Gumbo Beetroot</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner06.jpg" alt="img02" />
							<h3>Pea Sprouts Fava Soup</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner06.jpg" alt="img03" />
							<h3>Turnip Broccoli Sashimi</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner06.jpg" alt="img02" />
							<h3>Pea Sprouts Fava Soup</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner06.jpg" alt="img03" />
							<h3>Turnip Broccoli Sashimi</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner06.jpg" alt="img02" />
							<h3>Pea Sprouts Fava Soup</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner06.jpg" alt="img03" />
							<h3>Turnip Broccoli Sashimi</h3>
							<p>123</p>
						</li>

					</ul>
				</div>
			</section>
			<section id="section-2">
				<div class="custom-grid-pr">
					<ul class="product-list">
						<li class="big-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner02.jpg" alt="img01" />
							<h3>Sushi Gumbo Beetroot</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner02.jpg" alt="img02" />
							<h3>Pea Sprouts Fava Soup</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner02.jpg" alt="img03" />
							<h3>Turnip Broccoli Sashimi</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner02.jpg" alt="img02" />
							<h3>Pea Sprouts Fava Soup</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner02.jpg" alt="img03" />
							<h3>Turnip Broccoli Sashimi</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner02.jpg" alt="img02" />
							<h3>Pea Sprouts Fava Soup</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner02.jpg" alt="img03" />
							<h3>Turnip Broccoli Sashimi</h3>
							<p>123</p>
						</li>

					</ul>
				</div>
			</section>
			<section id="section-3">
				<div class="custom-grid-pr">
					<ul class="product-list">
						<li class="big-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner03.jpg" alt="img01" />
							<h3>Sushi Gumbo Beetroot</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner03.jpg" alt="img02" />
							<h3>Pea Sprouts Fava Soup</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner03.jpg" alt="img03" />
							<h3>Turnip Broccoli Sashimi</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner03.jpg" alt="img02" />
							<h3>Pea Sprouts Fava Soup</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner03.jpg" alt="img03" />
							<h3>Turnip Broccoli Sashimi</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner03.jpg" alt="img02" />
							<h3>Pea Sprouts Fava Soup</h3>
							<p>123</p>
						</li>
						<li class="small-product">
							<img src="http://127.0.0.1/m223_fastest/pub/media/wysiwyg/banner/banner03.jpg" alt="img03" />
							<h3>Turnip Broccoli Sashimi</h3>
							<p>123</p>
						</li>
					</ul>
				</div>
			</section>
		</div>
	</div>
</div>
-->
<script>
	require(["jquery","Magento_Theme/js/cbpFWTabs"], function($,Configurable){
		new CBPFWTabs( document.getElementById( 'tabs' ) );
	});
</script>



<!-- <p>{{block class="Magento\Catalog\Block\Product\ListProduct" name="category.products.list_home" as="product_list" column_count="4" products_count="3" category_id="3" template="Magento_Catalog::product/list_home.phtml"}}</p> -->




<!-- <p>{{widget type="Magento\Catalog\Block\Product\Widget\NewWidget" display_type="new_products" show_pager="0" products_count="10" template="product/widget/new/content/new_grid.phtml"}}</p>
<div class="main-advertisement hidden-xs">
	<div class="row">
		<div class="col-md-6 col-sm-12 col-xs-12">
			<div class="adver-content">
				<p class="adver-title">Nothing to hide here</p>
				<div class="adver-desc">
					<p>A bling pair of sandals is the corner stone of any girls outfit this season. Though high, the chunky platform and adjustable strap ensure a steady stride. Complement yours with darker tones.</p>
					<p><a class="view-more" href="#">view more</a></p>
				</div>
			</div>
		</div>
		<div class="col-md-6 col-sm-12  col-xs-12"><a href="#"><img src="{{media url="wysiwyg/img01.jpg"}}" alt="" /></a></div>
	</div>
</div>
<div class="main-advertisement">
	<div class="row">
		<div class="col-sm-6">
			<div class="row">
				<div class="col-sm-6  col-xs-6 col-first ">
					<div class="banner space-base"><a href="#"><img class="img-responsive" src="{{media url="wysiwyg/banner/banner01.jpg"}}" alt="Banner 01" /></a></div>
					<div class="banner"><a href="#"><img class="img-responsive" src="{{media url="wysiwyg/banner/banner02.jpg"}}" alt="Banner 02" /></a></div>
				</div>
				<div class="col-sm-6  col-xs-6 col-second">
					<div class="banner space-base"><a href="#"><img class="img-responsive" src="{{media url="wysiwyg/banner/banner03.jpg"}}" alt="Banner 03" /></a></div>
					<div class="banner"><a href="#"><img class="img-responsive" src="{{media url="wysiwyg/banner/banner04.jpg"}}" alt="Banner 04" /></a></div>
				</div>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="row">
				<div class="col-sm-6 col-xs-6 col-third">
					<div class="banner space-base"><a href="#"><img class="img-responsive" src="{{media url="wysiwyg/banner/banner05.jpg"}}" alt="Banner 05" /></a></div>
					<div class="banner"><a href="#"><img class="img-responsive" src="{{media url="wysiwyg/banner/banner06.jpg"}}" alt="Banner 06" /></a></div>
				</div>
				<div class="col-sm-6  col-xs-6 col-fourth">
					<div class="adver-content space-base">
						<p class="adver-title">Empire Deco High Level</p>
						<div class="adver-desc">
							<p>Discover the beautifully crafted Silverdale Empire Art Deco High Level Toilet online. Ideal for traditional settings</p>
							<p>Now available at Victorian Plumbing.</p>
							<p><a class="view-more" href="#">view more</a></p>
						</div>
					</div>
					<div class="banner"><a href="#"><img class="img-responsive" src="{{media url="wysiwyg/banner/banner07.jpg"}}" alt="Banner 07" /></a></div>
				</div>
			</div>
		</div>
	</div>
</div>
<p>{{widget type="Magefan\Blog\Block\Widget\Recent" title="All Articles, Our Blog" number_of_posts="10" category_id="0" custom_template="Magefan_Blog::widget/home-blog.phtml"}}{{widget type="Solwin\Instagram\Block\Widget\Instagram" title="#LivingSA Instagram" numberimage="10"}}</p> -->