<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
    $_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="post-list-wrapper blog-widget-recent">
    <h3 class="title"><?php echo $block->escapeHtml($block->getTitle()) ?></h3>
    <p class="title-desc"><span><?php echo __('Design news and Living style') ?></span></p>
    <ul class="slider-blog-home owl-carousel">
        <?php foreach ($_postCollection as $_post) { ?>
            <?php
                $_postUrl = $_post->getPostUrl();
                $_postName = $block->escapeHtml($_post->getTitle(), null, true);
            ?>
            <li class="post-holder-<?php echo $_post->getId() ?>">
                <div class="cdz-blog-top">
                    <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                        <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                            <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" height="380" width="380"/>
                        </a>
                    <?php } ?>
                    <div class="blog-home-date">
                        <span class="value"><?php echo $_post->getPublishDate('F d, Y') ?></span>
                    </div>
                </div>
                <div class="blog-home-bottom">
                    <h5 class="blog-title">
                        <a class="post-item-link" href="<?php echo $_postUrl ?>"><?php echo $_postName; ?>
                        </a>
                    </h5>
                    <div class="blog-desc">
                        <?php echo $block->getShorContent($_post) ?>
                    </div>
                    <p class="blog-text-link">
                        <a class="btn-link" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>"><span><?php echo __('&#187; Read more') ?></span></a>
                    </p>
                </div>
            </li>

        <?php } ?>
    </ul>
</div>
<?php } ?>