<?php /*echo $block->getChildHtml('product.info.mailto')*/ ?>
<!-- <div class="social-addthis">
	<a href="#" target="_blank">
		<span class="icon-facebook fa fa-facebook"></span>
	</a> 
	<a href="#" target="_blank">
		<span class="icon-twitter fa fa-twitter"></span>
	</a> 
	<a href="#"></span>
	</a> 
	<a href="#" target="_blank"><span class="icon-pinterest fa fa-pinterest-square"></span></a>
</div>
 -->
 <img src="http://127.0.0.1/m223_fastest/pub/static/version1521652852/frontend/Fastest/default/en_US/images/Zoe Outdoor.jpg" alt="">